//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be usefull. Share your emotions and thoughts from a visited place. Dynamically innovate resource-leveling customer service for state of the art customer service. Provide information about favourite places, interesting spots. Rate other, share your advices and thoughts. Make someones&apos; trip in Lviv easier and more comfortable..
        /// </summary>
        internal static string AboutFirstPharKey {
            get {
                return ResourceManager.GetString("AboutFirstPharKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only best reviews of Lviv restaurants, shops and other places.
        /// </summary>
        internal static string AboutHeaderKey {
            get {
                return ResourceManager.GetString("AboutHeaderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutKey {
            get {
                return ResourceManager.GetString("AboutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as private enterpreneur and create a profile for your restaurant/shop/other to promote and recieve honest feedbacks. Broaden your business and be open and clear for your costumers. The more true information you give, the more attention and visitors you wil receive..
        /// </summary>
        internal static string AboutSecondPharKey {
            get {
                return ResourceManager.GetString("AboutSecondPharKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have ability not only to help other tourists to find their best destination, you can become a bit responsible for developing better and more tourist-friendly city infrostucture..
        /// </summary>
        internal static string AboutThirdPharKey {
            get {
                return ResourceManager.GetString("AboutThirdPharKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        internal static string AddPhotoKey {
            get {
                return ResourceManager.GetString("AddPhotoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string BirthDateKey {
            get {
                return ResourceManager.GetString("BirthDateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafe.
        /// </summary>
        internal static string CafeTypeKey {
            get {
                return ResourceManager.GetString("CafeTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE PASSWORD.
        /// </summary>
        internal static string ChangePasswordKey {
            get {
                return ResourceManager.GetString("ChangePasswordKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        internal static string ClubTypeKey {
            get {
                return ResourceManager.GetString("ClubTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPasswordKey {
            get {
                return ResourceManager.GetString("ConfirmPasswordKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string ContactKey {
            get {
                return ResourceManager.GetString("ContactKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        internal static string CreateNewAccountKey {
            get {
                return ResourceManager.GetString("CreateNewAccountKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        internal static string EditKey {
            get {
                return ResourceManager.GetString("EditKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We didn&apos;t find any matching based on your filter.
        /// </summary>
        internal static string EmptyFilterResultKey {
            get {
                return ResourceManager.GetString("EmptyFilterResultKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastFood.
        /// </summary>
        internal static string FastFoodTypeKey {
            get {
                return ResourceManager.GetString("FastFoodTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to contact us in any time.
        /// </summary>
        internal static string FeelFreeToContactKey {
            get {
                return ResourceManager.GetString("FeelFreeToContactKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Profile.
        /// </summary>
        internal static string GoToProfileKey {
            get {
                return ResourceManager.GetString("GoToProfileKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string HelloKey {
            get {
                return ResourceManager.GetString("HelloKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeKey {
            get {
                return ResourceManager.GetString("HomeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        internal static string HotelTypeKey {
            get {
                return ResourceManager.GetString("HotelTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LoginKey {
            get {
                return ResourceManager.GetString("LoginKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string LogOFFKey {
            get {
                return ResourceManager.GetString("LogOFFKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        internal static string LOG_IN_KEY {
            get {
                return ResourceManager.GetString("LOG_IN_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing:.
        /// </summary>
        internal static string MarketingKey {
            get {
                return ResourceManager.GetString("MarketingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string MyProfileKey {
            get {
                return ResourceManager.GetString("MyProfileKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string NationalityKey {
            get {
                return ResourceManager.GetString("NationalityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not specified.
        /// </summary>
        internal static string NotSpecifiedKey {
            get {
                return ResourceManager.GetString("NotSpecifiedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordKey {
            get {
                return ResourceManager.GetString("PasswordKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string PhoneKey {
            get {
                return ResourceManager.GetString("PhoneKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Rate:.
        /// </summary>
        internal static string PleaseRateKey {
            get {
                return ResourceManager.GetString("PleaseRateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string RatingKey {
            get {
                return ResourceManager.GetString("RatingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        internal static string RegAsNewUserKey {
            get {
                return ResourceManager.GetString("RegAsNewUserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER AS OWNER.
        /// </summary>
        internal static string RegisterAsOwnerKey {
            get {
                return ResourceManager.GetString("RegisterAsOwnerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER AS REVIEWER.
        /// </summary>
        internal static string RegisterAsReviewerKey {
            get {
                return ResourceManager.GetString("RegisterAsReviewerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterKey {
            get {
                return ResourceManager.GetString("RegisterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        internal static string RemeberMeQuestionKey {
            get {
                return ResourceManager.GetString("RemeberMeQuestionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        internal static string RestaurantTypeKey {
            get {
                return ResourceManager.GetString("RestaurantTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string ReviewsKey {
            get {
                return ResourceManager.GetString("ReviewsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchBtnTitleKey {
            get {
                return ResourceManager.GetString("SearchBtnTitleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} stars.
        /// </summary>
        internal static string StarNumberKey {
            get {
                return ResourceManager.GetString("StarNumberKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Review.
        /// </summary>
        internal static string SubmitReviewKey {
            get {
                return ResourceManager.GetString("SubmitReviewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support:.
        /// </summary>
        internal static string SupportKey {
            get {
                return ResourceManager.GetString("SupportKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in your review.
        /// </summary>
        internal static string TypeInReviewKey {
            get {
                return ResourceManager.GetString("TypeInReviewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeKey {
            get {
                return ResourceManager.GetString("TypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use local account to log in.
        /// </summary>
        internal static string UseAccountToLogInKey {
            get {
                return ResourceManager.GetString("UseAccountToLogInKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeKey {
            get {
                return ResourceManager.GetString("WelcomeKey", resourceCulture);
            }
        }
    }
}
